[project]
name = "roimaintenence"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Matheus Jose", email = "viliczinskimatheusjose@gmail.com"},
]
dependencies = ["pymysql>=1.1.2", "django==4.1.13", "djangorestframework-simplejwt>=5.3.1", "djangorestframework==3.14.0"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
