# Generated by Django 4.2.16 on 2025-10-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaativos',
            options={'managed': False},
        ),
    ]
