# Generated by Django 4.2.16 on 2025-10-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintence', '0002_alter_categoriaativos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriaativos',
            table='categoriaativos',
        ),
    ]
