# Generated by Django 4.1.13 on 2025-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintence', '0003_alter_categoriaativos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('limiar_porcentagem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limiar_roi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_alerta', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'db_table': 'alertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id_ativo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ativo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_aquisicao', models.DateField()),
                ('vida_util_esperada', models.IntegerField()),
                ('unid_vida_util', models.CharField(max_length=20)),
                ('localizacao', models.CharField(max_length=150)),
                ('depreciacao_anual', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Ativo',
                'db_table': 'ativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAuditorias',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=100)),
                ('tabela_afetada', models.CharField(max_length=100)),
                ('id_reparo_afetado', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'db_table': 'logauditorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil_acesso', models.CharField(max_length=50)),
                ('re', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoriaativos',
            options={'managed': False, 'verbose_name': 'Categoria de Ativo'},
        ),
    ]
