# Generated by Django 4.1.13 on 2025-10-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintence', '0005_fornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome_peca', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Iten',
                'db_table': 'itens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensReparo',
            fields=[
                ('id_itemreparo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Item de Reparo',
                'db_table': 'itensreparo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'managed': False, 'verbose_name': 'Fornecedore'},
        ),
        migrations.CreateModel(
            name='Reparos',
            fields=[
                ('id_reparo', models.AutoField(primary_key=True, serialize=False)),
                ('data_reparo', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tempo_parada_hora', models.IntegerField()),
                ('extensao_vida_util', models.IntegerField()),
                ('unid_extensao_vida_util', models.CharField(max_length=20)),
                ('roi_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total_peca', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anexos', models.CharField(blank=True, max_length=255, null=True)),
                ('id_ativo', models.ForeignKey(db_column='id_ativo', on_delete=django.db.models.deletion.CASCADE, to='maintence.ativos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='maintence.usuarios')),
            ],
        ),
    ]
