# Generated by Django 4.1.13 on 2025-11-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintence', '0006_itens_itensreparo_alter_fornecedores_options_reparos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparos',
            options={'managed': False, 'verbose_name': 'Reparo'},
        ),
    ]
