# Generated by Django 4.1.13 on 2025-11-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintence', '0007_alter_reparos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reparos',
            table='reparos',
        ),
    ]
